### ISSUE TITLE
1st milestone

### ISSUE THREAD

**Issue by VladimirVisnovsky** [OtoFargas/Winery-Management-System#1]
### Requirements:
- [x] create a project in a Github repository that is publicly accessible (for reading). Select a short and descriptive name. Create some project wiki to publish additional information for your project.
- [x] on the project wiki there will be a project description, a use case diagram and a class diagram for the entity classes. There will be at least two user roles in the use case diagram. Associations between entities will be shown in a class diagram.  
- [x] the project will be built using maven: make sure you have all dependencies correctly configured, so it is possible to build and run the project from the command line.
- [x] show that you have been using pull requests in this milestone. The team leader will be responsible of managing pull requests.
- [x] every team member should work with different entities on different parts of the project (e.g. member 1 will create implementation of DAO for entity A, but member 2 will create test for entity A). In every class there will  be javadoc @author with the name of the class author. Also you must commit into Git only the changes that you made yourself. If you commit on behalf of somebody else this will not be regarded as his work!
- [x] create 4 entity classes for your project if you are a team of four (rule: one entity for each team member).
- [x] create a DAO layer interface (with proper Javadoc).
- [x] create the JPA implementation of the DAO classes (CRUD operations are enough for the first milestone).
- [x] create tests for the DAO classes (you can use an in-memory database).

**Comment by VladimirVisnovsky** [comment]
All done for first Milestone.
