### ISSUE TITLE
4th milestone

### ISSUE THREAD

**Issue by VladimirVisnovsky** [OtoFargas/Winery-Management-System#10]
Available dates and times will be listed in Information System in “Packages and topics” application. Only the team leader will sign up for the defense in the IS and must sign up for the time slot where his/her assigned seminar tutor will be present. All team members must be present. Please come 15 minutes in advance and make sure you set up all HW and SW to be ready to present your application on time (note: for online defences try to have all ready so that it can be shown by sharing the screen).

### 1. Requirements

- [x] Fix all mistakes and bugs in your project reported in the feedback given during the milestones. This has to be completed 72 hours before the start of your actual defense. You will be asked to show some portions of your source code at the defense, be prepared to do so;
- [x] Refine the GUI so that the presented application looks as appealing as possible;
- [x] dress code is casual;

### 2. Defence
Prepare slides and present your project to the committee. Also prepare answers to possible questions that your seminar tutor *might* send you in advance (latest 24 hours before defense). Your time limit for the defense is 15 minutes (no more, and this is strict), your presentation should be prepared for about 7 minutes and about 2 minutes should be live demo of your application.
Presentation should cover following topics:

- [ ] business logic (what is it for and what does it do);
- [ ] technologies used;
- [ ] team cooperation (who did what);
- [ ] your feedback (what did you like and what not in PA165);
- [ ] anything that you think should be considered worth bonus points, like some particular design of your project, the way a feature was implemented, usage of a specific framework, etc...
- [ ] if you need to pre-populate the application with some data, you can also use similar data generators as https://mockaroo.com
- [ ] To speed-up the remote session, please ensure that a) at least one of the team members (but see next point) has the project ready open in the IDE, b) that all the latest changes have been pushed to master branch, c) the project is already running before the start of the presentation. This should reduce waiting times for teams that follow.
- [ ] (online modality) The link to join the Zoom session will be published on this page, and sent via Slack. Please use name-surname-uco-teamname in Zoom, so it will be easier to follow the session;
- [ ] (online modality) Network issues can happen during a session, so potentially each team should be able to complete the presentation even if any of the team members has some issues.
