### ISSUE TITLE
2nd milestone

### ISSUE THREAD

**Issue by VladimirVisnovsky** [OtoFargas/Winery-Management-System#8]
### **1. Implement the Facade layer interfaces and implementations.**
- [x] Everything that should happen in the system must be available through these interfaces (creating entities, deleting them etc);
- [x] You must have at least two non-trivial business functions on Service Layer (the example project contains several of them). Service layer is not always just a place to delegate to DAOs;

### **2. Other points about the Facade and Service layers:**
- [x] All the classes must be wired via dependency injection. Your service objects should obtain an instance of the EntityManager that way;
- [x] All the facade interfaces must not reference entities, but Transfer Objects only;
- [x] All service interfaces must reference only entities, not Data Transfer Objects;
- [x] You can use the Dozer framework (or similar) to map entity instances to transfer objects. The mapping may be done on Facade Layer;
- [x] The Facade layer is used to drive transactions;

### **3. Change the layout of your project to a Multimodule Maven project (tutorial here http://maven.apache.org/guides/getting-started/index.html) Your project should have 3 separate modules:**
- [x] DAO layer
- [x] Service Layer and Facade Layer implementation
- [x] API layer - just DTOs and facade interfaces!

### **4. Rest of tasks:**
- [x] The Facade layer will use the Service layer and the Service layer will use the DAO layer;
- [x] Make sure that DataAccessException or its subclass is thrown in case of any exception on the DAO layer;
- [x] Implement simple unit tests for the facade layer. Just one simple test per method is enough. This is mainly so that it’s easy to verify the Facade layer;
- [x] There must be extensive unit tests for the service layer (particularly for your two business functions) and all the tests of the service layer must use Mock DAO objects;

**Comment by VladimirVisnovsky** [comment]
finished 2 milestone
