### ISSUE TITLE
3rd milestone

### ISSUE THREAD

**Issue by VladimirVisnovsky** [OtoFargas/Winery-Management-System#9]
### 1. User interface

- [x] To start the web application you have to configure maven plugin. It is very important that it will be possible to start the web application from the command line. For example using the Cargo plugin with Tomcat, the following sequence of commands should start the web application: “mvn clean install && cd web && mvn cargo:run”. (Please note that Spring since version 5 does not work in Tomcat 7, so the maven tomcat7 plugin is not usable with recent versions of Spring. Use maven Cargo plugin with a recent version of Tomcat. See the example project in the master branch.)
- [x] The web application must be available at the following HTTP context http://localhost:8080/pa165
- [x] Your application should use in-memory database. This means that after application restart (killing web container and starting it again with mvn cargo:run) the data may be reset.
- [x] Implement the user interface using Spring MVC, or a Javascript framework like Angular, React or Vue.js. 
- [x] The user interface should allow to carry out all business functions of your system.
- [x] You should fill in all the necessary data automatically. So for example you can use a Web Listener to load data during Web Application startup.
- [x] Make sure there are validations implemented at the user interface level.
- [x] Your user interface should use either a Facade layer or REST layer to access the system. Do not directly access database and do not directly use the Service layer.
- [x] The web interface layer may reside in a separate maven module (if this is helpful).
- [x] Each member of the team must implement (mostly independently) part of user interface. Including controllers and views.

### 2. REST layer:

- [x] Your application should have a basic REST interface/API.
- [x] At least one entity and operations on that entity must be exposed. 
This is mainly to demonstrate you can implement this, it is not necessary to have all application functions accessible through this interface.
- [x] The REST API must be accessible at http://localhost:8080/pa165/rest
- [x] It is not required to have the interface secured.
- [x] You should include a README file with instructions about how to test the REST interface (e.g. CURL commands for the command line).

### 3. Security:

- [x] There should be at least two roles in the system (e.g. Administrator, User). Each role should have some differences in user interface or in capabilities.
- [x] There should be a login form (not HTTP Basic)
- [x] Registration is NOT required. You can prefill the users and their passwords in the database.
- [x] Password should not be saved in the database in open form.
